[package]
name = 'move-to-learn-nft'
version = "1.0.0"
authors = []

[addresses]
dev = "0x09e088a2b6825eeaa03f923d7e99116951f666cc1a8cfabd5969751c12e49dbc"
aptos_framework = "0x1"
aptos_token_objects = "0x4"  # Token Objects 的标准地址
[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "main" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-token-objects", rev = "main" }

[dev-dependencies]
